[keyboard]
name = "Keybow2040_T9"
product_name = "Keybow2040_T9"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[rmk]
morse_max_num = 16
max_patterns_per_key = 8

[storage]
clear_storage = true

[matrix]
matrix_type = "direct_pin"
direct_pins = [
    ["PIN_18", "PIN_14", "PIN_10", "PIN_6"],
    ["PIN_19", "PIN_15", "PIN_11", "PIN_7"],
    ["PIN_20", "PIN_16", "PIN_12", "PIN_8"],
    ["PIN_21", "PIN_17", "PIN_13", "PIN_9"]
]


[layout]
rows = 4
cols = 4
layers = 1
keymap = [
    [
        ["A", "TD(0)", "TD(1)", "X"],
        ["B", "F", "G", "H"],
        ["C", "J", "K", "L"],
        ["D", "N", "O", "P"]
    ]
]


[behavior.morse]
hold_timeout = "300ms"
gap_timeout = "2000ms"

morses = [
  # TD(0): numpad 1
  { morse_actions = [
      { pattern = "-", action = "Kc1" },
    ]},
  # TD(1): numpad 2
  { morse_actions = [
      { pattern = "-", action = "Kc2" },
      { pattern = ".", action = "A" },
      { pattern = ".-", action = "A" },
      { pattern = "..", action = "B" },
      { pattern = "..-", action = "B" },
      { pattern = "...", action = "C" },
      { pattern = "...-", action = "C" },
    ]}
]


